dist: trusty
sudo: required
language: node_js
node_js:
	- "9.11"

matrix:
  include:
    - os: linux
      dist: trusty
      before_install:
      - npm install -g truffle ganache-cli

script: 
- ganache-cli >/dev/null 2>&1 &
- truffle test 
